/* ==========================================================================
   coffees.js — the single data file for the whole catalog.

   Everything the site knows lives here: recipes, milks, syrups, tips, machine
   info, official standards and sources. To add a coffee, add one entry to
   `recipes` (see the helper functions right below) — no other file needs to
   change.

   Units: ml for liquids, g for ice / ice cream. One espresso shot = 25 ml
   (the Italian Espresso National Institute reference: 7 g of coffee -> 25 ml
   in the cup). A "double" is 2 shots = 50 ml. 1 syrup pump = 10 ml.
   ========================================================================== */
window.COFFEE_DATA = (function () {
  "use strict";

  /* ---- tiny helpers so recipes stay readable ----------------------------- */
  const E   = (ml) => ({ t: "espresso", ml });          // espresso
  const M   = (ml) => ({ t: "milk", ml });              // steamed (hot) / cold (iced) milk
  const F   = (ml) => ({ t: "foam", ml });              // milk foam
  const CF  = (ml) => ({ t: "coldfoam", ml });          // cold milk foam
  const W   = (ml) => ({ t: "water", ml });             // water
  const I   = (g)  => ({ t: "ice", g });                // ice
  const SY  = (id, ml) => ({ t: "syrup", id, ml });     // syrup (see `syrups`)
  const SA  = (id, ml) => ({ t: "sauce", id, ml });     // sauce (see `syrups`, kind: "sauce")
  const L   = (t, ml) => ({ t, ml });                   // any other liquid (tonic, oj, chai, ...)
  const IC  = (g)  => ({ t: "icecream", g });           // ice cream
  const TOP = (kind) => ({ t: "top", kind });           // topping: whipped, cocoa, cinnamon, cayenne, caramel, chocolate, seasalt
  const GAR = (kind) => ({ t: "garnish", kind });       // garnish: orange, lemon, lime, mint, cinnamon-stick

  /* ---- ingredient types (colours used by the cup illustration) ----------- */
  const types = {
    espresso:  { label: "Espresso",          color: "#3a2012", liquid: true },
    water:     { label: "Water",             color: "#e9dcc6", liquid: true },
    milk:      { label: "Milk",              color: "#f2e4cb", liquid: true },
    foam:      { label: "Milk foam",         color: "#fbf3e3", liquid: true },
    coldfoam:  { label: "Cold foam",         color: "#fdf7ea", liquid: true },
    cremafoam: { label: "Espresso foam",     color: "#c58f55", liquid: true },
    syrup:     { label: "Syrup",             color: "#d9a95a", liquid: true },
    sauce:     { label: "Sauce",             color: "#4a2618", liquid: true },
    condensed: { label: "Condensed milk",    color: "#eed9a4", liquid: true },
    chai:      { label: "Chai concentrate",  color: "#a4672f", liquid: true },
    tonic:     { label: "Tonic water",       color: "#e3eee9", liquid: true },
    oj:        { label: "Orange juice",      color: "#f3a53b", liquid: true },
    lemonade:  { label: "Lemonade",          color: "#f4e58a", liquid: true },
    lime:      { label: "Lime juice",        color: "#dfe9a0", liquid: true },
    soda:      { label: "Sparkling water",   color: "#dcebf0", liquid: true },
    icecream:  { label: "Vanilla ice cream", color: "#f8ecd0", liquid: false },
    ice:       { label: "Ice",               color: "#dff1ff", liquid: false },
  };

  /* ---- syrups & sauces ---------------------------------------------------
     Written for Monin-style flavouring syrups, but any brand works.
     `homemade: true` = no standard bottle exists, recipe given in the tips.  */
  const syrups = [
    { id: "vanilla",           label: "Vanilla",            color: "#e8c27a", kind: "syrup", group: "Sweet & creamy" },
    { id: "caramel",           label: "Caramel",            color: "#b9722c", kind: "syrup", group: "Sweet & creamy" },
    { id: "salted-caramel",    label: "Salted caramel",     color: "#c0812f", kind: "syrup", group: "Sweet & creamy" },
    { id: "hazelnut",          label: "Hazelnut",           color: "#a86b3c", kind: "syrup", group: "Nutty" },
    { id: "pistachio",         label: "Pistachio",          color: "#a9c283", kind: "syrup", group: "Nutty" },
    { id: "coconut",           label: "Coconut",            color: "#f1e6d2", kind: "syrup", group: "Nutty" },
    { id: "amaretto",          label: "Amaretto (alcohol-free)", color: "#c7894a", kind: "syrup", group: "Nutty" },
    { id: "irish-cream",       label: "Irish cream (alcohol-free)", color: "#c9a27a", kind: "syrup", group: "Sweet & creamy" },
    { id: "brown-sugar",       label: "Brown sugar",        color: "#8d5a30", kind: "syrup", group: "Sweet & creamy" },
    { id: "maple",             label: "Maple",              color: "#b8681e", kind: "syrup", group: "Sweet & creamy" },
    { id: "honey",             label: "Honey",              color: "#e5a72e", kind: "syrup", group: "Sweet & creamy" },
    { id: "toasted-marshmallow", label: "Toasted marshmallow", color: "#e6c9a0", kind: "syrup", group: "Sweet & creamy" },
    { id: "cinnamon",          label: "Cinnamon",           color: "#b0471f", kind: "syrup", group: "Spiced", spicy: true },
    { id: "gingerbread",       label: "Gingerbread",        color: "#9a5a2a", kind: "syrup", group: "Spiced", spicy: true },
    { id: "pumpkin",           label: "Pumpkin spice",      color: "#d9822b", kind: "syrup", group: "Spiced", spicy: true },
    { id: "cardamom",          label: "Cardamom (homemade)", color: "#c9a85f", kind: "syrup", group: "Spiced", spicy: true, homemade: true },
    { id: "chili-honey",       label: "Chili honey (homemade)", color: "#d6521f", kind: "syrup", group: "Spiced", spicy: true, homemade: true },
    { id: "lavender",          label: "Lavender",           color: "#a58fc4", kind: "syrup", group: "Floral & fresh" },
    { id: "peppermint",        label: "Peppermint",         color: "#bfe3d0", kind: "syrup", group: "Floral & fresh" },
    { id: "mint",              label: "Mint / mojito",      color: "#9fd6a5", kind: "syrup", group: "Floral & fresh" },
    { id: "sugar",             label: "Simple (sugar) syrup", color: "#f2e6cc", kind: "syrup", group: "Basics" },
    { id: "chocolate",         label: "Chocolate sauce",    color: "#4a2618", kind: "sauce", group: "Sauces" },
    { id: "white-chocolate",   label: "White chocolate sauce", color: "#eedfba", kind: "sauce", group: "Sauces" },
    { id: "caramel-sauce",     label: "Caramel sauce",      color: "#a8621f", kind: "sauce", group: "Sauces" },
    { id: "condensed",         label: "Sweetened condensed milk", color: "#eed9a4", kind: "sauce", group: "Sauces" },
  ];

  /* ---- milks & alternatives ---------------------------------------------- */
  const milks = [
    { id: "whole",    label: "Whole milk",       short: "Whole",    dairy: true,  color: "#f2e4cb", foam: 5,
      note: "The reference milk. Sweet, creamy and the easiest to turn into silky microfoam.",
      steam: "Steam to 60–65 °C. Stretch for 3–5 s for a latte, 8–10 s for a cappuccino." },
    { id: "semi",     label: "Semi-skimmed",     short: "Semi",     dairy: true,  color: "#f3e7d2", foam: 4,
      note: "Lighter body, still foams well. Slightly less sweet than whole.",
      steam: "Same technique as whole milk; foam is a little airier and drier." },
    { id: "skim",     label: "Skimmed milk",     short: "Skim",     dairy: true,  color: "#f5ecda", foam: 4,
      note: "Makes big, stiff foam quickly but tastes thinner and the foam is less glossy.",
      steam: "Stretch for less time — it over-aerates fast. Stop at 60 °C." },
    { id: "lactosefree", label: "Lactose-free",  short: "Lactose-free", dairy: true, color: "#f2e4cb", foam: 5,
      note: "Naturally sweeter (lactose is pre-split). Behaves like whole/semi milk.",
      steam: "Steam like normal milk, but it browns/scalds sooner — stop at 60 °C." },
    { id: "oat",      label: "Oat (barista)",    short: "Oat",      dairy: false, color: "#eddcb8", foam: 4,
      note: "Best all-round plant milk: creamy, naturally sweet, good microfoam. Use a “barista” edition.",
      steam: "Steam to 55–60 °C only; it thickens and goes gluey if overheated. Short stretch (2–3 s)." },
    { id: "soy",      label: "Soy (barista)",    short: "Soy",      dairy: false, color: "#f0e2bf", foam: 4,
      note: "High protein, foams well. Can curdle in very hot, acidic coffee.",
      steam: "Keep it at 55–60 °C. Pour the milk into the cup first, or let the espresso cool a few seconds, to avoid splitting." },
    { id: "almond",   label: "Almond",           short: "Almond",   dairy: false, color: "#efe0c5", foam: 2,
      note: "Nutty and light, but thin — foam is bubbly and collapses quickly.",
      steam: "Steam gently to 55 °C, minimal air (1–2 s), and pour right away. Barista editions help a lot." },
    { id: "coconut",  label: "Coconut",          short: "Coconut",  dairy: false, color: "#f7f0e4", foam: 2,
      note: "Tropical flavour, thin foam. Wonderful with vanilla or coconut syrup.",
      steam: "Steam to 55 °C with very little air. Pick a barista/“for coffee” coconut drink, not the canned kind." },
  ];

  /* ---- toppings (used by recipes and the customiser) --------------------- */
  const toppings = [
    { id: "whipped",   label: "Whipped cream",     color: "#fffaf0" },
    { id: "cocoa",     label: "Cocoa dust",        color: "#5a3420" },
    { id: "cinnamon",  label: "Cinnamon",          color: "#a4531f", spicy: true },
    { id: "cayenne",   label: "Pinch of cayenne",  color: "#c8321d", spicy: true },
    { id: "caramel",   label: "Caramel drizzle",   color: "#b9722c" },
    { id: "chocolate", label: "Chocolate drizzle", color: "#3a1c10" },
    { id: "seasalt",   label: "Sea salt flakes",   color: "#ffffff" },
  ];

  /* ---- the recipes -------------------------------------------------------
     Ingredient order = layer order from the BOTTOM of the glass to the TOP.
     shots    -> number of espresso shots (drives caffeine)
     layered  -> keep layers crisp instead of blending them
     blend    -> visually mix espresso/water/syrups into one colour
     basis    -> "standard" (official/industry reference) | "classic" (café
                 convention) | "flavoured" (syrup dosing per Monin guidance)
                 | "creative" (modern café / house recipe)
     src      -> keys of `sources` below                                       */
  const recipes = [
    /* ===================== ESPRESSO FAMILY ============================== */
    { id: "espresso", name: "Espresso", alt: "Caffè", temp: "hot", shots: 1, basis: "standard", src: ["inei", "wiki"],
      ing: [E(25)], vessel: "demi", tags: ["classic", "italian"],
      desc: "The heart of everything: a small, syrupy shot topped with hazelnut-coloured crema.",
      origin: "Italy",
      tip: "Official Italian target: 7 g of coffee → 25 ml in 25 s at ~88 °C. On the Dedica use the single (1-cup) button and stop at ~25–30 ml." },
    { id: "doppio", name: "Doppio", alt: "Double espresso", temp: "hot", shots: 2, basis: "standard", src: ["inei", "sca"],
      ing: [E(50)], vessel: "demi", tags: ["classic", "italian"],
      desc: "Two shots in one cup — the base of most café milk drinks.",
      origin: "Italy",
      tip: "Use the double basket and the 2-cup button. Around 14 g in → 50 ml out in 25–30 s." },
    { id: "ristretto", name: "Ristretto", alt: "Restricted shot", temp: "hot", shots: 1, basis: "standard", src: ["wiki-ristretto"],
      ing: [E(20)], vessel: "demi", tags: ["classic", "italian"],
      desc: "A shorter, sweeter, more concentrated shot — less bitterness, more body.",
      origin: "Italy",
      tip: "Same dose as an espresso, but stop the pump at ~15–20 ml (about 15–20 s)." },
    { id: "lungo", name: "Lungo", alt: "Long shot", temp: "hot", shots: 1, basis: "standard", src: ["wiki-ristretto"],
      ing: [E(60)], vessel: "demi", tags: ["classic", "italian"],
      desc: "A ‘long’ pull with roughly twice the water — lighter body, more bitterness and a bit more caffeine.",
      origin: "Italy",
      tip: "Let the pump run to ~60 ml. If it tastes harsh, use a slightly coarser grind or cooler temperature setting." },
    { id: "macchiato", name: "Espresso Macchiato", alt: "Caffè macchiato", temp: "hot", shots: 1, basis: "classic", src: ["wiki", "cb"],
      ing: [E(25), F(10)], vessel: "demi", tags: ["classic", "italian"],
      desc: "Espresso ‘stained’ with a spoonful of milk foam — strong, with just a soft edge.",
      origin: "Italy",
      tip: "Spoon 1–2 tsp (~10 ml) of dense foam on top. Steam a small amount of milk with a little extra air." },
    { id: "romano", name: "Espresso Romano", alt: "Romano", temp: "hot", shots: 1, basis: "classic", src: ["wiki"],
      ing: [E(25), GAR("lemon")], vessel: "demi", tags: ["classic", "italian"],
      desc: "Espresso served with a twist of lemon peel — bright, aromatic and refreshing.",
      tip: "Rub the peel around the rim (don’t drop juice in). Serve with a saucer and a little sugar on the side." },
    { id: "con-panna", name: "Espresso con Panna", alt: "Viennese-style espresso", temp: "hot", shots: 1, basis: "classic", src: ["wiki"],
      ing: [E(25), TOP("whipped")], vessel: "demi", tags: ["classic", "dessert"],
      desc: "A shot crowned with a cloud of whipped cream. Bitter and sweet in one sip.",
      tip: "Use lightly sweetened, softly whipped cream so it floats on the crema." },
    { id: "cortado", name: "Cortado", alt: "Gibraltar (US)", temp: "hot", shots: 2, basis: "classic", src: ["cb", "wiki-cortado"],
      ing: [E(50), M(50)], vessel: "short", tags: ["classic", "spanish"],
      desc: "Equal parts espresso and warm milk. ‘Cortado’ means ‘cut’ — the milk cuts the espresso’s edge.",
      origin: "Spain",
      tip: "1 : 1 ratio. Steam the milk to ~60 °C with almost no air — you want it silky, not foamy." },
    { id: "cappuccino", name: "Cappuccino", alt: "Cappuccio", temp: "hot", shots: 2, basis: "standard", src: ["sca", "cb"],
      ing: [E(50), M(50), F(50)], tags: ["classic", "italian"],
      desc: "The classic ‘thirds’ drink: one part espresso, one part steamed milk, one part thick foam.",
      origin: "Italy",
      tip: "SCA definition: 150–180 ml total with at least ~1 cm of foam. Stretch the milk for 8–10 s to build the airy top." },
    { id: "flat-white", name: "Flat White", alt: "", temp: "hot", shots: 2, basis: "standard", src: ["cb", "sca"],
      ing: [E(50), M(110), F(20)], tags: ["classic", "australian"],
      desc: "Velvety microfoam over a double espresso — stronger and less foamy than a latte.",
      origin: "Australia / New Zealand",
      tip: "Only ~5 mm of microfoam. Stretch for just 2–3 s, then roll the milk until glossy like wet paint." },
    { id: "latte", name: "Caffè Latte", alt: "Latte", temp: "hot", shots: 2, basis: "standard", src: ["cb", "wiki"],
      ing: [E(50), M(170), F(30)], tags: ["classic", "italian"],
      desc: "Silky and mellow: a double espresso in lots of steamed milk with a thin cap of foam.",
      origin: "Italy",
      tip: "Roughly 1 : 4 espresso to milk, ~1 cm foam. A perfect base for syrups and latte art." },
    { id: "latte-macchiato", name: "Latte Macchiato", alt: "Stained milk", temp: "hot", shots: 1, basis: "classic", src: ["wiki"],
      ing: [M(150), E(25), F(30)], layered: true, vessel: "tall", tags: ["classic", "italian"],
      desc: "The reverse of a macchiato: milk first, then espresso poured through the foam for beautiful layers.",
      origin: "Italy",
      tip: "Pour the espresso slowly down the inside of the glass (or over a spoon) so it sits between milk and foam." },
    { id: "americano", name: "Caffè Americano", alt: "Americano", temp: "hot", shots: 2, basis: "classic", src: ["wiki", "cb"],
      ing: [E(50), W(130)], blend: true, tags: ["classic", "black"],
      desc: "Espresso lengthened with hot water — the closest espresso gets to filter coffee.",
      tip: "Hot water from a kettle at ~90 °C (or the wand’s hot-water function if your Dedica has one). Add water to the espresso." },
    { id: "long-black", name: "Long Black", alt: "", temp: "hot", shots: 2, basis: "classic", src: ["wiki"],
      ing: [W(130), E(50)], layered: true, tags: ["classic", "black", "australian"],
      desc: "Like an Americano in reverse: the espresso goes on top of the water so the crema stays intact.",
      origin: "Australia / New Zealand",
      tip: "Pour ~90 °C water into a warm cup first, then pull the double shot straight onto it." },
    { id: "mocha", name: "Caffè Mocha", alt: "Mochaccino", temp: "hot", shots: 2, basis: "classic", src: ["cb", "wiki"],
      ing: [SA("chocolate", 25), E(50), M(140), F(25), TOP("whipped")], tags: ["classic", "sweet", "dessert"],
      desc: "A latte with chocolate — coffee and hot chocolate in one cup.",
      tip: "Pull the espresso onto the chocolate sauce and stir before adding milk so it doesn’t sink and stick." },
    { id: "piccolo", name: "Piccolo Latte", alt: "Piccolo", temp: "hot", shots: 1, basis: "classic", src: ["wiki"],
      ing: [E(20), M(50), F(10)], vessel: "short", tags: ["classic", "australian"],
      desc: "A ristretto in a tiny glass topped with warm, silky milk. Small but mighty.",
      tip: "Steam only ~60 ml of milk in a small jug. Ideal after dinner when you want something gentler than an espresso." },
    { id: "bombon", name: "Café Bombón", alt: "Bombón", temp: "hot", shots: 1, basis: "classic", src: ["wiki"],
      ing: [L("condensed", 25), E(25)], layered: true, vessel: "short", tags: ["classic", "spanish", "sweet", "dessert"],
      desc: "Sweetened condensed milk with espresso poured on top — two clean layers in a small glass.",
      origin: "Valencia, Spain",
      tip: "Use a clear glass. Pull the shot slowly over the back of a spoon so the layers stay separate; stir at the end." },
    { id: "affogato", name: "Affogato", alt: "Affogato al caffè", temp: "hot", shots: 2, basis: "classic", src: ["wiki"],
      ing: [IC(70), E(50)], vessel: "short", tags: ["classic", "italian", "dessert"],
      desc: "‘Drowned’ vanilla ice cream — hot espresso poured over a cold scoop. Dessert and coffee at once.",
      origin: "Italy",
      tip: "Pour the espresso right after it’s pulled so the ice cream melts at the edge. One scoop = about 70 g." },

    /* ===================== FLAVOURED & SPICED (HOT) ===================== */
    { id: "vanilla-latte", name: "Vanilla Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin", "cb"],
      ing: [SY("vanilla", 20), E(50), M(150), F(30)], tags: ["sweet"],
      desc: "The friendly favourite: a classic latte with 2 pumps of vanilla syrup.",
      tip: "Put the syrup in the cup first and pull the espresso onto it so it dissolves completely." },
    { id: "caramel-latte", name: "Caramel Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("caramel", 20), E(50), M(150), F(30), TOP("caramel")], tags: ["sweet"],
      desc: "Buttery caramel through the milk and a ribbon of caramel over the foam.",
      tip: "Warm the drizzle bottle in hot water for a few seconds so it flows in thin lines." },
    { id: "hazelnut-latte", name: "Hazelnut Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("hazelnut", 20), E(50), M(150), F(30)], tags: ["sweet"],
      desc: "Toasty, nutty and dessert-like. Tastes like a Nutella-adjacent hug.",
      tip: "Add a dusting of cocoa on top or swap 5 ml of the syrup for chocolate sauce." },
    { id: "salted-caramel-latte", name: "Salted Caramel Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("salted-caramel", 20), E(50), M(150), F(30), TOP("caramel"), TOP("seasalt")], tags: ["sweet"],
      desc: "Sweet caramel with a savoury salt edge that makes every sip more interesting.",
      tip: "Finish with 3–4 flakes of sea salt on the foam — not a pinch, or it turns harsh." },
    { id: "pistachio-latte", name: "Pistachio Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("pistachio", 20), E(50), M(150), F(30)], tags: ["sweet"],
      desc: "Smooth, green and buttery — a marzipan-meets-nut latte that pairs beautifully with oat milk.",
      tip: "Try 15 ml pistachio + 5 ml vanilla for a rounder flavour." },
    { id: "coconut-latte", name: "Coconut Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("coconut", 20), E(50), M(150), F(30)], milk: "coconut", tags: ["sweet"],
      desc: "Tropical and creamy; best with coconut or oat milk for a fully dairy-free treat.",
      tip: "Keep the milk at ~55 °C; coconut drinks are thin, so stretch for only 1–2 s." },
    { id: "irish-cream-latte", name: "Irish Cream Latte (0 %)", alt: "Alcohol-free", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("irish-cream", 20), E(50), M(150), F(30), TOP("cocoa")], tags: ["sweet"],
      desc: "The cosy cream-liqueur taste using an alcohol-free Irish cream syrup.",
      tip: "Dust with cocoa; a pinch of nutmeg on top makes it smell like a pub at Christmas." },
    { id: "gingerbread-latte", name: "Gingerbread Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("gingerbread", 20), E(50), M(150), F(30), TOP("whipped"), TOP("cinnamon")], tags: ["sweet", "spicy", "seasonal"],
      desc: "Ginger, cinnamon and molasses in a cup. Warming and just a little bit spicy.",
      tip: "Dust with cinnamon over the whipped cream for extra aroma." },
    { id: "pumpkin-spice-latte", name: "Pumpkin Spice Latte", alt: "PSL", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("pumpkin", 25), E(50), M(140), F(30), TOP("whipped"), TOP("cinnamon")], tags: ["sweet", "spicy", "seasonal"],
      desc: "Autumn in a mug: pumpkin, cinnamon, nutmeg and clove with steamed milk.",
      origin: "USA",
      tip: "Pumpkin spice syrups are milder than caramel, so 25 ml (2.5 pumps) works well." },
    { id: "honey-cinnamon-latte", name: "Honey Cinnamon Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("honey", 15), SY("cinnamon", 5), E(50), M(150), F(30), TOP("cinnamon")], tags: ["sweet", "spicy"],
      desc: "Floral honey and a whisper of cinnamon — mellow, comforting and not too sweet.",
      tip: "Pull the espresso onto the syrups and stir; honey sinks if left alone." },
    { id: "lavender-honey-latte", name: "Lavender Honey Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("lavender", 15), SY("honey", 10), E(50), M(150), F(25)], tags: ["sweet"],
      desc: "Soft floral lavender balanced with honey. Elegant, calming and café-worthy.",
      tip: "Lavender is strong — stay at 15 ml or it tastes like soap." },
    { id: "maple-cinnamon-latte", name: "Maple Cinnamon Latte", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("maple", 20), SY("cinnamon", 5), E(50), M(145), F(30), TOP("cinnamon")], tags: ["sweet", "spicy"],
      desc: "Pancake-morning vibes: maple sweetness with a cinnamon kick.",
      tip: "Great with oat milk, which adds a toasty grain sweetness." },
    { id: "toasted-marshmallow-mocha", name: "Toasted Marshmallow Mocha", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SA("chocolate", 20), SY("toasted-marshmallow", 15), E(50), M(130), F(25), TOP("whipped")], tags: ["sweet", "dessert"],
      desc: "Campfire s’mores as a mocha: chocolate, toasted sugar and whipped cream.",
      tip: "Torch the whipped cream lightly (or run a hot spoon over it) for a real toasted top." },
    { id: "peppermint-mocha", name: "Peppermint Mocha", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SA("chocolate", 25), SY("peppermint", 10), E(50), M(130), F(25), TOP("whipped"), TOP("chocolate")], tags: ["sweet", "dessert", "seasonal"],
      desc: "Chocolate mint — like an after-eight in a cup. A winter classic.",
      tip: "Peppermint is potent: 10 ml is plenty. Too much tastes like toothpaste." },
    { id: "white-mocha", name: "White Chocolate Mocha", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SA("white-chocolate", 30), E(50), M(140), F(20), TOP("whipped")], tags: ["sweet", "dessert"],
      desc: "Sweet, creamy white chocolate with the bite of a double espresso.",
      tip: "White chocolate sauce is very sweet; balance with a slightly darker roast." },
    { id: "spanish-latte", name: "Spanish Latte", alt: "Café con leche condensada", temp: "hot", shots: 2, basis: "flavoured", src: ["wiki"],
      ing: [SA("condensed", 30), E(50), M(150), F(20)], tags: ["sweet", "spanish"],
      desc: "A latte sweetened with condensed milk: rich, caramel-y and silky.",
      origin: "Spain",
      tip: "Stir the condensed milk into the espresso before pouring the milk. No extra sugar needed." },
    { id: "caramel-macchiato", name: "Caramel Macchiato", alt: "", temp: "hot", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("vanilla", 20), M(150), E(50), F(30), TOP("caramel")], layered: true, vessel: "tall", tags: ["sweet"],
      desc: "Vanilla, steamed milk, espresso poured through the foam, and a lattice of caramel on top.",
      tip: "Don’t stir — the layers are the point. Pour the shot in a slow circle to ‘mark’ the foam." },
    { id: "mexican-mocha", name: "Mexican Spiced Mocha", alt: "Spicy mocha", temp: "hot", shots: 2, basis: "creative", src: ["monin"],
      ing: [SA("chocolate", 25), SY("cinnamon", 10), E(50), M(130), F(25), TOP("cinnamon"), TOP("cayenne")], tags: ["spicy", "sweet", "dessert"],
      desc: "Chocolate, cinnamon and a whisper of cayenne that warms the back of your throat.",
      origin: "Mexico-inspired",
      tip: "Use less than 1/8 tsp cayenne — mix it into the chocolate sauce first so it doesn’t sit on top as dust." },
    { id: "cafe-de-olla-latte", name: "Café de Olla Latte", alt: "", temp: "hot", shots: 2, basis: "creative", src: ["monin"],
      ing: [SY("brown-sugar", 20), SY("cinnamon", 10), E(50), M(140), F(30), GAR("cinnamon-stick")], tags: ["spicy", "sweet"],
      desc: "Inspired by Mexican café de olla — brown sugar, cinnamon and a hint of orange in a latte.",
      origin: "Mexico-inspired",
      tip: "Twist a strip of orange peel over the foam to release its oils before serving." },
    { id: "cardamom-latte", name: "Cardamom Latte", alt: "", temp: "hot", shots: 2, basis: "creative", src: ["monin"],
      ing: [SY("cardamom", 20), E(50), M(150), F(30)], tags: ["spicy", "sweet"],
      desc: "Aromatic and floral, in the spirit of Middle-Eastern and Scandinavian cardamom coffees.",
      tip: "No bottle syrup? Simmer 100 g sugar, 100 ml water and 6 crushed green pods for 5 minutes, then strain." },
    { id: "hot-honey-latte", name: "Hot Honey Latte", alt: "Spicy honey latte", temp: "hot", shots: 2, basis: "creative", src: ["monin"],
      ing: [SY("honey", 15), E(50), M(155), F(30), TOP("cayenne")], tags: ["spicy", "sweet"],
      desc: "Honey sweetness with a slow heat at the end. Surprisingly addictive.",
      tip: "A tiny pinch of cayenne or chili flakes is all it takes — start with a couple of grains." },
    { id: "dirty-chai", name: "Dirty Chai Latte", alt: "Chai + espresso", temp: "hot", shots: 2, basis: "creative", src: ["cb"],
      ing: [L("chai", 60), E(50), M(110), F(30), TOP("cinnamon")], tags: ["spicy", "sweet"],
      desc: "Spiced chai latte ‘dirtied’ with a double shot of espresso — ginger, cardamom, cinnamon and coffee.",
      tip: "Use a chai concentrate at roughly 1 : 1 with milk. Heat the concentrate with the milk when steaming, or pour it in first." },

    /* ===================== ICED & COLD ================================== */
    { id: "iced-americano", name: "Iced Americano", alt: "", temp: "iced", shots: 2, basis: "classic", src: ["cb"],
      ing: [I(150), E(50), W(130)], blend: true, tags: ["classic", "black"],
      desc: "Clean, crisp and refreshing: double espresso over cold water and ice.",
      tip: "Fill the glass with ice and cold water first, then pull the shot over it so the crema swirls through." },
    { id: "iced-latte", name: "Iced Latte", alt: "", temp: "iced", shots: 2, basis: "classic", src: ["cb"],
      ing: [I(150), M(170), E(50)], layered: true, tags: ["classic"],
      desc: "Cold milk and ice with a double shot poured on top — pretty layers and an easy sip.",
      tip: "Let the espresso cool for 20 seconds before pouring so it melts less ice and the layers stay defined." },
    { id: "iced-mocha", name: "Iced Mocha", alt: "", temp: "iced", shots: 2, basis: "classic", src: ["cb"],
      ing: [SA("chocolate", 25), M(150), E(50), I(150), TOP("whipped")], tags: ["sweet", "dessert"],
      desc: "Chocolate, espresso and cold milk over ice with a whipped-cream crown.",
      tip: "Whisk the chocolate sauce with the hot espresso first — it won’t dissolve in cold milk." },
    { id: "iced-vanilla-latte", name: "Iced Vanilla Latte", alt: "", temp: "iced", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("vanilla", 20), M(160), E(50), I(150)], layered: true, tags: ["sweet"],
      desc: "Sweet vanilla, cold milk and espresso — the easy-drinking summer default.",
      tip: "Add 5 ml more syrup than you would for a hot drink; cold dulls sweetness." },
    { id: "iced-caramel-macchiato", name: "Iced Caramel Macchiato", alt: "", temp: "iced", shots: 2, basis: "flavoured", src: ["monin"],
      ing: [SY("vanilla", 20), M(170), I(120), E(50), TOP("caramel")], layered: true, tags: ["sweet"],
      desc: "Vanilla at the bottom, milk and ice in the middle, espresso on top and caramel over it all.",
      tip: "Build in this order — syrup, milk, ice, espresso, drizzle — and don’t stir." },
    { id: "brown-sugar-oat-shaken-espresso", name: "Brown Sugar Oat Shaken Espresso", alt: "", temp: "iced", shots: 2, basis: "creative", src: ["cb"],
      ing: [SY("brown-sugar", 20), E(50), M(60), I(100), TOP("cinnamon")], blend: true, milk: "oat", tags: ["sweet", "spicy"],
      desc: "Espresso shaken with brown sugar and ice until frothy, then topped with a splash of oat milk.",
      tip: "Shake espresso, syrup and 3 ice cubes hard for 10 seconds in a shaker or jar, strain over fresh ice, then add the oat milk." },
    { id: "espresso-tonic", name: "Espresso Tonic", alt: "", temp: "iced", shots: 2, basis: "creative", src: ["cb"],
      ing: [I(120), L("tonic", 150), E(50), GAR("orange")], layered: true, tags: ["black", "sparkling"],
      desc: "Sparkling, bittersweet and refreshing. Espresso floats on tonic like a sunset.",
      origin: "Sweden",
      tip: "Pour the tonic over ice first, then slowly pour the espresso over the back of a spoon. Garnish with orange peel." },
    { id: "bumble-coffee", name: "Bumble Coffee", alt: "Espresso + orange juice", temp: "iced", shots: 2, basis: "creative", src: ["cb"],
      ing: [I(150), L("oj", 100), E(50), GAR("orange")], layered: true, tags: ["black", "fruity"],
      desc: "Cold orange juice topped with espresso: bright citrus up front, chocolate-y coffee after.",
      tip: "Use fresh, low-pulp orange juice, well chilled. Lighter, fruitier roasts taste best here." },
    { id: "espresso-lemonade", name: "Espresso Lemonade", alt: "", temp: "iced", shots: 2, basis: "creative", src: ["cb"],
      ing: [I(150), L("lemonade", 130), E(50), GAR("lemon")], layered: true, tags: ["black", "fruity"],
      desc: "Tart lemonade with a shot of espresso — surprisingly balanced and very refreshing.",
      tip: "Use a not-too-sweet lemonade. Pour the espresso last and slowly to keep the layers." },
    { id: "coffee-mojito", name: "Coffee Mojito (0 %)", alt: "Mint espresso soda", temp: "iced", shots: 2, basis: "creative", src: ["monin"],
      ing: [SY("mint", 15), L("lime", 15), L("soda", 110), I(150), E(50), GAR("mint"), GAR("lime")], layered: true, tags: ["black", "sparkling", "fruity"],
      desc: "Mint, lime and sparkling water with an espresso float. Alcohol-free and super fresh.",
      tip: "Slap the mint leaves in your hand to wake up the oils, then drop them in with the syrup and lime." },
    { id: "freddo-espresso", name: "Freddo Espresso", alt: "", temp: "iced", shots: 2, basis: "classic", src: ["wiki"],
      ing: [SY("sugar", 10), E(50), L("cremafoam", 20), I(100)], blend: true, tags: ["classic", "black", "greek"],
      desc: "Greece’s summer staple: a double espresso shaken with ice until foamy and chilled.",
      origin: "Greece",
      tip: "Shake espresso and sugar syrup with ice for 15 seconds, then strain into a glass over fresh ice." },
    { id: "freddo-cappuccino", name: "Freddo Cappuccino", alt: "", temp: "iced", shots: 2, basis: "classic", src: ["wiki"],
      ing: [SY("sugar", 10), E(50), CF(100), I(100)], blend: true, tags: ["classic", "greek"],
      desc: "A freddo espresso capped with thick cold milk foam. Iced cappuccino, Greek style.",
      origin: "Greece",
      tip: "The Dedica wand can’t make cold foam — whip ~80 ml of cold milk with a handheld frother for 20–30 s." },
    { id: "iced-spanish-latte", name: "Iced Spanish Latte", alt: "", temp: "iced", shots: 2, basis: "flavoured", src: ["wiki"],
      ing: [SA("condensed", 30), M(150), E(50), I(150)], layered: true, tags: ["sweet", "spanish"],
      desc: "Condensed milk at the bottom, cold milk in the middle and espresso on top; stir to enjoy.",
      tip: "Give it a good stir before the first sip — the sweet layer sits on the bottom." },
    { id: "ca-phe-sua-da", name: "Cà Phê Sữa Đá", alt: "Vietnamese-style iced coffee", temp: "iced", shots: 2, basis: "classic", src: ["wiki"],
      ing: [SA("condensed", 40), E(50), I(150)], layered: true, tags: ["classic", "sweet", "vietnamese"],
      desc: "Very strong coffee sweetened with condensed milk over ice. Traditionally made with a phin filter.",
      origin: "Vietnam",
      tip: "A ristretto-style double gives the closest flavour on the Dedica. Stir well, then add ice." },
    { id: "iced-lavender-oat-latte", name: "Iced Lavender Oat Latte", alt: "", temp: "iced", shots: 2, basis: "creative", src: ["monin"],
      ing: [SY("lavender", 15), M(170), E(50), I(150)], layered: true, milk: "oat", tags: ["sweet"],
      desc: "Floral lavender and creamy oat milk over ice — light, calming and pretty in a glass.",
      tip: "Oat milk is naturally sweet, so 15 ml of lavender syrup is plenty." },
    { id: "iced-cinnamon-brown-sugar-latte", name: "Iced Cinnamon Brown Sugar Latte", alt: "", temp: "iced", shots: 2, basis: "creative", src: ["monin"],
      ing: [SY("brown-sugar", 15), SY("cinnamon", 10), M(160), E(50), I(150), TOP("cinnamon")], tags: ["sweet", "spicy"],
      desc: "Caramel-y brown sugar with a cinnamon kick. Warm spices, cold glass.",
      tip: "Stir the syrups into the hot espresso before it hits the milk." },
    { id: "iced-hot-honey-latte", name: "Iced Hot Honey Latte", alt: "Spicy honey iced latte", temp: "iced", shots: 2, basis: "creative", src: ["monin"],
      ing: [SY("chili-honey", 20), M(170), E(50), I(150)], layered: true, tags: ["spicy", "sweet"],
      desc: "Sweet honey with a slow chili heat over cold, creamy milk.",
      tip: "Chili honey: warm 100 g honey with ½ tsp chili flakes for 5 minutes, then strain. Use 20 ml." },
  ];

  /* ---- tips (the “Tips” button) ------------------------------------------ */
  const tips = [
    { id: "milk", icon: "🥛", title: "Steaming milk on the Dedica",
      intro: "The Dedica Arte has a manual steam wand (“My LatteArt”), so results come down to technique. Practice with a cup of water and a drop of dish soap before wasting milk.",
      items: [
        { h: "Start cold", p: "Use fridge-cold milk (~4 °C) and a cold stainless-steel pitcher. Cold milk gives you more time to add air before it gets hot." },
        { h: "Fill the pitcher right", p: "Fill to just under the base of the spout (about one third to half full). Milk expands 20–40 % when you add air, so leave room." },
        { h: "Purge first", p: "Open the steam for 1–2 seconds pointing into the drip tray to clear condensed water, and again right after you’re done." },
        { h: "Position the tip", p: "Put the tip just under the surface, slightly off-centre, and tilt the pitcher a little so the milk spins in a whirlpool." },
        { h: "Stretch (add air)", p: "Keep the tip near the surface until you hear a soft “tss-tss”. About 2–3 s for a flat white, 3–5 s for a latte, 8–10 s for a cappuccino." },
        { h: "Roll (make it silky)", p: "Sink the tip deeper so the milk rolls smoothly and the bubbles disappear. Stop when the pitcher is too hot to hold for more than ~3 seconds — about 60–65 °C." },
        { h: "Finish", p: "Switch off the steam, wipe the wand with a damp cloth immediately, purge once more, then tap the pitcher on the counter and swirl until glossy. Pour within 10–15 seconds." },
        { h: "Right temperature", p: "The SCA range for milk drinks is 55–65 °C. Above 70 °C milk tastes flat and scalded and the sweetness disappears." },
      ] },
    { id: "espresso", icon: "☕", title: "Pulling a good shot",
      intro: "Official Italian espresso: 7 g of coffee, 88 °C, 9 bar, 25 seconds, 25 ml in the cup. Your Dedica uses a 15-bar pump and pressurised baskets that forgive a lot, but the same logic applies.",
      items: [
        { h: "Preheat everything", p: "Run a blank shot of water through the empty portafilter and cup before brewing, and keep cups on the top warmer. Cold cups steal heat from a 25 ml shot fast." },
        { h: "Dose and level", p: "Single basket ≈ 7 g, double ≈ 14 g (the double basket holds up to ~16 g). Level the grounds and tamp evenly." },
        { h: "Time it", p: "Aim for 25–30 seconds. Under 15 s and sour/thin: grind finer or tamp firmer. Over 40 s and bitter/dry: grind coarser or use less coffee." },
        { h: "Pods & pre-ground", p: "The Dedica accepts ESE pods and pre-ground coffee with the pressurised basket. A non-pressurised basket + fresh, fine-ground beans gives better cups but needs a proper grinder." },
        { h: "Fresh beans", p: "Use beans roasted within the last 2–6 weeks, stored airtight and away from light. Grind just before brewing." },
        { h: "Temperature setting", p: "The Dedica Arte has 3 temperature levels: go higher for light roasts and milk drinks, lower for very dark roasts that turn bitter." },
        { h: "Ristretto & lungo", p: "Stop the pump early (~20 ml) for a ristretto, or let it run to ~60 ml for a lungo. Same dose, different water." },
      ] },
    { id: "iced", icon: "🧊", title: "Iced & cold drinks",
      intro: "Cold changes flavour — sweetness and aroma both dull — so iced recipes are built a little bolder.",
      items: [
        { h: "Use plenty of ice", p: "A packed glass melts slower than a half-full one. Use ~150 g of large cubes for a 350 ml glass; small cubes water the drink down." },
        { h: "Chill the glass", p: "Fill it with ice and water for a minute while you pull the shot." },
        { h: "Sweeten the hot part", p: "Stir syrup into the fresh espresso where it dissolves instantly. Sugar doesn’t dissolve well in cold liquid." },
        { h: "Layer on purpose", p: "For pretty layers: syrup → cold milk → ice → espresso poured slowly over the back of a spoon. For a blended taste, stir or shake." },
        { h: "Shaken espresso", p: "Shake espresso, syrup and 3 ice cubes for 10–15 s. You’ll get a chilled, foamy, slightly diluted shot." },
        { h: "Cold foam", p: "The Dedica steam wand can’t make cold foam. Whip ~80 ml of very cold milk (low-fat or barista oat) with a handheld frother for 20–30 s." },
        { h: "Espresso tonic", p: "Pour the espresso slowly over the back of a spoon onto tonic + ice for the sunset effect. Fast pours mix and foam over." },
      ] },
    { id: "syrup", icon: "🍯", title: "Syrups, sauces & spices",
      intro: "Standard dosing is 2 pumps (about 20 ml) of syrup per 240 ml (8 oz) of drink. Pumps vary between brands — measure yours once.",
      items: [
        { h: "Pump = 10 ml", p: "This site assumes 1 pump ≈ 10 ml. Monin lists 1 pump at roughly ¼ fl oz (~7 ml) while many café guides use 10 ml — weigh your pump once and adjust." },
        { h: "Sizes", p: "Small (180–240 ml): 15–20 ml. Medium (350 ml): 25–30 ml. Large (450 ml): 30–40 ml. Iced drinks: add a bit more because cold dulls sweetness." },
        { h: "Syrup first", p: "Put syrup in the cup, then pull the espresso onto it. It dissolves without stirring and coats the cup evenly." },
        { h: "Sauces (thick)", p: "Chocolate, white chocolate and caramel sauce dissolve best in hot espresso. Whisk or stir before adding milk." },
        { h: "Flavour pairing", p: "Caramel + sea salt · vanilla + cinnamon · hazelnut + chocolate · lavender + honey · maple + cinnamon · orange + espresso." },
        { h: "Adding heat", p: "Spicy coffee: cayenne, chili honey or ground ginger. Use a few grains to 1/8 tsp — mix into syrup or chocolate first. Never put spice in a pressurised portafilter; it can clog." },
        { h: "Homemade syrup", p: "Simple syrup: 100 g sugar + 100 ml water, simmer until dissolved. For spice: add 2 cinnamon sticks, 6 crushed cardamom pods or 1 tsp grated ginger, simmer 5 min, strain. Keeps 2 weeks in the fridge." },
        { h: "Sugar-free & 0 %", p: "Most syrup brands offer sugar-free versions. Alcohol-free Irish-cream and amaretto syrups give the taste without the spirit." },
      ] },
    { id: "milks", icon: "🌱", title: "Oat, soy, almond & other milks",
      intro: "Plant milks work great — choose “barista” editions, which have added fat/stabilisers so they steam without splitting.",
      items: [
        { h: "Ranking for foam", p: "Whole milk > oat (barista) ≈ soy (barista) > semi/skim > almond > coconut." },
        { h: "Lower the temperature", p: "Steam plant milks to 55–60 °C. They thicken, split or taste burnt when they get too hot." },
        { h: "Less air", p: "Give plant milks a short stretch (1–3 s). Then focus on rolling the milk to get small, tight bubbles." },
        { h: "Prevent curdling", p: "Soy and some almond milks can split in hot, acidic coffee. Pour the milk into the cup first, or let the espresso cool for a few seconds." },
        { h: "Shake the carton", p: "Plant milks separate. Shake well before pouring, and use them soon after opening." },
        { h: "Flavour matches", p: "Oat → caramel, brown sugar, cinnamon. Soy → vanilla, chocolate. Almond → hazelnut, amaretto. Coconut → vanilla, coconut, chocolate." },
      ] },
    { id: "fix", icon: "🛠️", title: "Troubleshooting & care",
      intro: "Quick fixes for common problems.",
      items: [
        { h: "Sour or thin shot", p: "Grind finer, use a bit more coffee, use a higher temperature setting, or run the shot a little longer." },
        { h: "Bitter or burnt shot", p: "Grind coarser, use less coffee, lower the temperature setting, or stop the shot earlier." },
        { h: "Big soap-like bubbles", p: "You added too much air or kept the tip too high. Purge, dive the tip a bit deeper and tap/swirl the jug." },
        { h: "Milk too hot", p: "Stop at 60–65 °C. If you overshoot, you can’t fix it; start again with fresh cold milk." },
        { h: "Weak steam / sputtering", p: "Wait for the steam indicator to be ready before opening the knob, and purge condensation first. Descale if it happens regularly." },
        { h: "Every day", p: "Wipe the steam wand right after use, purge, rinse the portafilter and basket, empty the drip tray, and refill the tank with fresh water." },
        { h: "Every few months", p: "Descale following the manual (more often with hard water) and run a couple of tank rinses afterwards." },
      ] },
  ];

  /* ---- the Dedica Arte fact sheet ---------------------------------------- */
  const machine = {
    name: "De’Longhi Dedica Arte (EC885)",
    specs: [
      { k: "Pump pressure",  v: "15 bar (pump maximum; the espresso standard is ~9 bar at the coffee)", src: "delonghi" },
      { k: "Heating",        v: "Thermoblock — heats up in about 1–2 minutes", src: "delonghi" },
      { k: "Power",          v: "1300 W", src: "delonghi-spec" },
      { k: "Dimensions",     v: "149 × 330 × 305 mm (W × D × H)", src: "delonghi-spec" },
      { k: "Weight",         v: "4.2 kg", src: "delonghi-spec" },
      { k: "Steam wand",     v: "Manual steam wand with “My LatteArt” system for microfoam & latte art", src: "delonghi" },
      { k: "Temperature",    v: "3-level brew temperature control", src: "delonghi" },
      { k: "Portafilter",    v: "Pressurised baskets (single & double); works with ground coffee and ESE pods. Double basket holds up to ~16 g.", src: "delonghi" },
      { k: "Extras",         v: "Metal tamper included; cup-warming tray on top", src: "delonghi" },
    ],
    note: "Facts above were found in the manufacturer/retailer listings linked in the sources. Details I couldn’t confirm (cup clearance, water tank size, hot-water function) are deliberately not listed — check your manual."
  };

  /* ---- official numbers used across the site ----------------------------- */
  const standards = [
    { k: "Ground coffee per espresso", v: "7 g ± 0.5 g", src: "inei" },
    { k: "Water temperature (at exit)", v: "88 °C ± 2 °C", src: "inei" },
    { k: "Water pressure", v: "9 bar ± 1", src: "inei" },
    { k: "Extraction time", v: "25 s ± 5 s", src: "inei" },
    { k: "Volume in the cup (incl. crema)", v: "25 ml ± 2.5 ml", src: "inei" },
    { k: "Temperature in the cup", v: "67 °C ± 3 °C", src: "inei" },
    { k: "Caffeine per Italian espresso", v: "under 100 mg", src: "inei" },
    { k: "Ristretto", v: "≈ 20 ml (shorter pull)", src: "wiki-ristretto" },
    { k: "Lungo", v: "≈ 60 ml (longer pull)", src: "wiki-ristretto" },
    { k: "Macchiato", v: "≈ 30–40 ml total", src: "wiki" },
    { k: "Cappuccino (SCA)", v: "150–180 ml, at least ~1 cm microfoam", src: "sca" },
    { k: "Flat white", v: "double espresso (≈ 50 ml) + ≈ 130 ml milk", src: "sca" },
    { k: "Caffè latte", v: "≈ 250 ml, espresso : milk ≈ 1 : 3 to 1 : 5", src: "wiki" },
    { k: "Milk temperature (SCA)", v: "55–65 °C", src: "sca" },
    { k: "Espresso brew ratio", v: "1 : 1 to 1 : 2 (dose : yield)", src: "sca" },
    { k: "Syrup dose", v: "≈ 20 ml (2 pumps) per 240 ml / 8 oz", src: "monin" },
    { k: "Caffeine per espresso shot", v: "≈ 63 mg per 30 ml (commonly cited)", src: "mayo" },
  ];

  /* ---- sources ----------------------------------------------------------- */
  const sources = {
    "inei":   { title: "Espresso — parameters of the Italian Espresso National Institute (INEI)", url: "https://en.wikipedia.org/wiki/Espresso", note: "7 g, 88 °C, 9 bar, 25 s, 25 ml, 67 °C in the cup, < 100 mg caffeine. Cross-checked with the Home-Barista and Mokaffee articles below." },
    "inei-hb": { title: "Home-Barista — What is traditional Italian espresso", url: "https://www.home-barista.com/knockbox/what-is-traditional-italian-espresso-t68306.html", note: "Second reference for the INEI parameters." },
    "wiki":   { title: "Wikipedia — Espresso (and linked drink articles)", url: "https://en.wikipedia.org/wiki/Espresso", note: "Drink definitions and typical volumes (macchiato, latte, americano, affogato, mocha…)." },
    "wiki-ristretto": { title: "Wikipedia — Ristretto / Lungo", url: "https://en.wikipedia.org/wiki/Ristretto", note: "Short (≈ 20 ml) and long (≈ 60 ml) pulls of the same dose." },
    "wiki-cortado": { title: "Wikipedia — Cortado", url: "https://en.wikipedia.org/wiki/Cortado", note: "Equal parts espresso and warm milk." },
    "sca":    { title: "Perfect Daily Grind — Standardising the size of coffee milk drinks", url: "https://perfectdailygrind.com/2026/07/standardise-size-of-coffee-milk-drinks-flat-white/", note: "Reports the SCA definitions: cappuccino 150–180 ml, 55–65 °C milk, 1 : 1–1 : 2 espresso ratio." },
    "cb":     { title: "Coffee Bros — Espresso drinks explained", url: "https://coffeebros.com/blogs/coffee/espresso-drinks-explained-cappuccino-vs-latte-vs-flat-white-vs-cortado", note: "Espresso : milk : foam ratios for macchiato, cortado, flat white, cappuccino, latte and mocha." },
    "monin":  { title: "Monin — How to use Monin syrup pumps (plus retailer dosing guides)", url: "https://monin.us/blogs/blog/how-to-use-monin-syrup-pumps-pump-care-101", note: "2 pumps (≈ 20 ml) per 8 oz; 3 per 12 oz; 4 per 16 oz. Pump output varies by bottle." },
    "monin-guide": { title: "Font Coffee Roasters — Latte syrup ratio guide", url: "https://font-mag.com/blogs/news/coffee-syrup-ratio-guide-lattes", note: "15–20 ml for a 12 oz latte, 20–25 ml for 16 oz." },
    "delonghi": { title: "Tools & Toys — De’Longhi EC885 Dedica Arte review", url: "https://toolsandtoys.net/delonghi-ec885-dedica-arte-espresso-machine/", note: "15-bar pump, thermoblock, metal tamper, warm-up time." },
    "delonghi-spec": { title: "Manualshelf — Dedica Arte EC885M specification sheet", url: "https://www.manualshelf.com/manual/delonghi/ec885m/specifications-sheet-english.html", note: "Dimensions, weight and power." },
    "mayo":   { title: "Mayo Clinic — Caffeine content for coffee, tea, soda and more", url: "https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/caffeine/art-20049372", note: "Espresso ≈ 63 mg per 1 fl oz. (Widely quoted; the page blocked automated access when this site was built.)" },
  };

  return { types, syrups, milks, toppings, recipes, tips, machine, standards, sources,
           consts: { shotMl: 25, pumpMl: 10, caffeinePerShot: 63, decafPerShot: 4 } };
})();
